### ISSUE TITLE
Auto position fail

### ISSUE THREAD

**Issue by seltix5** [tempusdominus/bootstrap-3#8] opened 2017-05-18 10:54 UTC
hi,
the auto position is not working correctly :
![untitled-1](https://cloud.githubusercontent.com/assets/11258096/26199102/b556e9c0-3bc0-11e7-9283-5c7397973922.jpg)

thanks ^^

**Comment by Eonasdan** [comment] 2017-06-24 22:38
Looks like a duplicate of #4. Closing

**Closed by Eonasdan** 2017-06-24 22:38 UTC
